### ISSUE TITLE
is it possible to run lapis from another directory?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#256]
if I have my application in some directory, say 'app_dir' and I run 'lapis server' from that directory, a bunch of other files are created- directories like 'logs', 'scgi_temp', etc are generated by the running of the application.  These files aren't really part of the application.

Is there some way of specifying the application directory from a different working directory in order to keep the application files (views, static, app.lua) separate from the runtime-generated files?  For example, if I had another directory called 'run_dir' that was a peer of app_dir, perhaps somehow the command from the command-line reference could resolve to something like

nginx -p run_dir/ -c "app_dir/nginx.conf"

in order to put all the temp files in run_dir

**Comment by leafo** [comment]
You can add your other directory to the lua loadpath. It needs to be available as soon as lapis starts so the config can be found and loaded (note if it doesn't find a config it will continue on with no error, so you might get confused)

There are many ways to set the loadpath, you can do it within lua, using `lua.path` and `lua.cpath`, or you can use `LUA_PATH` and `LUA_CPATH` environment variables.

For example, this should work using the environment variable approach:

```bash
LUA_PATH='someapp/?.lua;;' lapis server
```

The `nginx.conf` file still needs to be in the root nginx directory, otherwise the lapis command won't find it.

**Comment by nelson2005** [comment]
thanks, that's most of what I want- I'll poke around to see if I can figure out how to make it work for nginx.conf as well.
