### ISSUE TITLE
Splat question

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#273]
I'm trying to use splatting like the example at 

http://leafo.net/lapis/reference/actions.html#request-object-methods-build_urlpath-options

I have ```app:match('/edit_project/*', require('actions.edit_project_get'))``` but when I try to hit that URL, I get an error: ..../application.lua:393: Failed to find route: /choose_project?dir=okay

I've tried other combinations, such as naming the route, using ```app:match('/edit_project*'```, but haven't managed to get it running.  Am I missing something?

**Comment by leafo** [comment]
`choose_project` != `edit_project` ?

Also the splat `/hello_world/` will only match things that start with `/hello_world/` (note the trailing slash)

You could creating two routes that go to same action.

`/hello_world` and `/hello_world/*`

**Comment by leafo** [comment]
The splat URL matcher is in need of some serious upgrades though. If we want to start collecting complaints/struggles in a single issue I can reference it when I work on the URL matcher next

**Comment by nelson2005** [comment]
Sorry, that was a typo in the original question.  using "/edit_project?dir=okay" still has the same error, but if I use "/choose_project/?dir=okay" it'll route okay.  Here's how it looks to me:

route '/edit_project*' matches "/edit_project/?dir=okay" and doesn't match "/edit_project?dir=okay"
route '/edit_project/*' matches neither "/edit_project/?dir=okay" nor "/edit_project?dir=okay"
route '/edit_project' matches both "/edit_project/?dir=okay" and "/edit_project?dir=okay" (splat is nil)

So overall, I'm kind of at a loss of how to use the splatting at all.  I poked about on the net, didn't see any working examples.  It seems like it does need a bit of attention like you mention.  I think just being able to handle the basic syntax of "/some_url?arg1=hello"  would be a good start.

**Comment by leafo** [comment]
The URL patterns only match the path, not the query parameters.

The route `/hello` would match `/hello` `/hello?` `/hello?one=two` etc. Any query parameters can optionally be appended to the URL.

The splat `/hello/*` is similar to the regex: `^\/hello\/.*$`, meaning the trailing / is required. The splat does is not effected by query parameters at all. As with any route, they can be optionally added to a URL.

Lapis has a default action: if there is a path that has a trailing `/` and it doesn't match anything, it will strip the `/` and try again. That's why if you have the route `/edit_project` and you navigate to `/edit_project/` you'll notice a 301 browser redirect to `/edit_project`.

If your routes specifically mention the `/` then the trailing `/` strip won't happen. I wasn't able to reproduce the case for you where `/edit_project/` didn't match `/edit_project/`. I just added some specs covering some of these cases.

**Comment by VaiN474** [comment]
you don't need to define query parameters in a route (i.e. "?foo=bar&bin=bash"), these can be captured from any route using `self.params`
```lua
-- /edit_project?dir=okay
app:get("edit","/edit_project", function(self)
    return (self.params and self.params.dir or "No 'dir' param in URL")
end)
```
Splats are intended to be used as a catch-all for params that you may not know the name of or have too many to make routes for. If you know what, and how many, then you should define the routes instead.
```lua
-- /edit_project/okay
app:get("edit","/edit_project/:dir", function(self)
    return self.params.dir
end)
```
splat:
```lua
-- /edit_project/path/that/is/not/known/
app:get("edit","/edit_project/*", function(self)
    return self.params.splat -- you would have to split this yourself
end)
```

**Comment by leafo** [comment]
PS edited comment above a bunch to be less confusing

**Comment by nelson2005** [comment]
Thanks to both leafo and VaiN474.  My understanding was wrong.  I thought the splat was for picking up query parameters and didn't understand that the routing and the parameters were unrelated.  I don't know of any problem with the splat routing.

**Comment by nelson2005** [comment]
BTW, what happens if a user specifies a query parameter that matches a route?  For example, using VaiN474's example

``-- /edit_project/okay
app:get("edit","/edit_project/:dir", function(self)
    return self.params.dir
end)``

what is the value of self.params.dir if the user calls /edit_project/okay?dir=not_okay
