### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by lee-kagiso** [leafo/lapis#356]
Is it possible to log 500 errors automatically to a file along with the access log and maybe to the console output with `lapis server`?

**Comment by leafo** [comment]
Since lapis catches errors to show an error page it doesn't bubble up to nginx. I don't know any way to write to the error log manually. You can write to the notice log using the `print` function, but there are limitations on the length of the print output.

If you're only looking to see errors in development when the server is running in the foregroud, another approach is to write to `stdout`
