### ISSUE TITLE
Error when app doesn't exist?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#429]
Can we please make Lapis error if you attempt to serve a non-existent app?

I realize this is completely my own fault, but I set up everything.. except for forgetting to compile the moonscript files, and no errors. I try to connect, "connection refused", still no errors, I think my nginx config must be wrong, I start playing with it for hours trying to figure out why one app runs and another doesn't, and finally realize my mistake.

I feel like this is the kind of noob mistake that should be caught..

**Comment by leafo** [comment]
You're referring to this line? `require("lapis").serve("app")` in the nginx config that should error when `app` doesn't exist?

It should already error, but since it's not inside lapis yet it will be captured by nginx and be written to the notice log, along with showing nginx's default 500 error page

**Comment by Guard13007** [comment]
Hmm..that's probably exactly what happened but I didn't notice it. That's definitely clear enough (if I just wasn't so dumb xD)
