### ISSUE TITLE
Detach lapis models from lapis?

### ISSUE THREAD

**Issue by italomaia** [leafo/lapis#580]
Would it be reasonable to have Lapis ORM as a package independent from lapis? As there are few ORMs for Lua, maybe that would be helpful.

**Comment by leafo** [comment]
you can use the model class class outside of lapis with no issues. Just `require 'lapis.db.model' to get access to it.

Lapis also has database connection management but you can swap that out by changing the `db` object stored on the model's classs

**Comment by italomaia** [comment]
The question is: would it have value as a project on its own? There are few ORM options for lua.

**Comment by leafo** [comment]
I'm not a fan of splitting things up because it makes deploying much harder. I don't want to have to manage incrementing rockspecs when I'm working on a development version of lapis.

**Comment by italomaia** [comment]
Fair enough. Thanks for replying.

**Comment by nonchip** [comment]
> you can use the model class class outside of lapis with no issues. Just `require 'lapis.db.model' to get access to it.

not without `lapis.config` though. is there any way to use the lapis ORM *without* lapis, but just pgmoon for example?

**Comment by italomaia** [comment]
Truth be told: lua, the lang, doesn't have a robust ORM package available out of the box.

**Comment by nonchip** [comment]
and lapis's ORM is pretty much the only great thing about lapis left since @leafo seems to be ignoring each and every problem with it. so yeah if he doesn't want to modularize it, I'm afraid I'll just have to fork it and throw away all the unnecessary parts he claimed above it wouldn't be depending on while for plain laziness it does anyway... If I do, I'll include it in my modular framework https://github.com/cuddlyrobot/dysnomia some time soon you can use the "lapis-liberated version" either with it or just standalone (with pgmoon or whatever).

**Comment by leafo** [comment]
I'm sorry you feel that way @nonchip. The things I prioritize aren't related to making money. (I can't tell if you're being sarcastic). I use it every day on multiple projects. Sometimes I work on things for fun because they interest me (widget optimizer, which is first test of moonscript AST transformer syntax using tableshape). The installation depends on the OS you're using, installation was not broken, people ran into issues for certain configurations of openssl. And I have no idea what you're talking about regarding critical security stuff ignored for years. There are definitely some enhancements that I'd like to address with CSRF and the session signatures but nothing that would lead to the compromise of an app is left outstanding. (if there is contact me privately)

In any case, it doesn't sound like you're being constructive. If you're here to advertise your own projects and call me lazy then I'll have to remove your posts. If you're just messing with me then maybe I missed the joke.

**Comment by leafo** [comment]
> not without lapis.config though. is there any way to use the lapis ORM without lapis, but just pgmoon for example?

Ii depends on configuration module for the default database connection in `lapis/db/postgres.moon`. 

The simplest approach to get around this would be to make a new backend that doesn't look at config. It's technically possible to this with the undocumented `raw` backend:

```lua
require("lapis.db.postgres"):set_backend("raw", function() 
  -- return bound query and disconnect methods from pgmoon here
end)

-- using model will no longer try to connect with config
local Model = require("lapis.db.postgres.model").Model
Model:extend() -- etc.

-- note we can't use shortcut module `lapis.db.model` because it checks config for db type
```

I didn't test this, so give it a shot. If this is something that you'd like as part of the public API then we can add it to docs.

**Comment by nonchip** [comment]
> The installation depends on the OS you're using, installation was not broken, people ran into issues for certain configurations of openssl.

it was. I clearly remember it being unable to install on both libressl and openssl1.1 => broken on everything but not-updated OSses

> And I have no idea what you're talking about regarding critical security stuff ignored for years. There are definitely some enhancements that I'd like to address with CSRF and the session signatures but nothing that would lead to the compromise of an app is left outstanding. (if there is, contact me privately)

csrf, signatures, HMAC_SHA1 being strange, ...

> In any case, it doesn't sound like you're being constructive. If you're here to advertise your own projects and call me lazy then I'll have to remove your posts. If you're just messing with me then maybe I missed the joke.

sorry for that, I'm afraid those posts' tone is influenced by the facts a) I last tried to use lapis when being unable to install it because of openssl nastiness while under time pressure, b) feeling annoyed by statements like "it doesn't depend on anything" while it actually does, and c) I just realized I'm catching a cold which probably didn't do my temper any good.

I'm not trying to advertise my own projects but just stating where I'll fork the ORM module to when uncluttering its dependencies and why I felt the need to start that project. Wouldn't do any good if I just said "yeah I'll do that but can't/won't tell you where" so I hope you excuse the open self-plug there.

**Comment by leafo** [comment]
> it was. I clearly remember it being unable to install on both libressl and openssl1.1 => broken on everything but not-updated OSses

You needed openssl 1.0 to install it. I don't think that's too unreasonable given many distros provide 1.0 packages, and Openresty itself depends on openssl 1.0. Just an unfortunate consequence of distros upgrading packages.

> csrf

There's a issue if you don't provide a key to the CSRF function. ideally lapis should be responsible for generating the key, sorry I haven't updated this yet.

> signatures, HMAC_SHA1

All strings are signed with hmac sha1, as far as I know the collision vulnerabilities do not affect hmac-sha1, many cloud providers and two factor auth systems still use hmac-sha1. Upgrading to sha256 would be nice but I need to add a migration system so existing apps don't break.

> sorry for that

It's okay, I was just a little confused. I don't mind your advertising your project, it's just that if it's combined with attacks against this project then I'm going to have to say something.

> feeling annoyed by statements like "it doesn't depend on anything" while it actually does

Sorry about that, I didn't get a chance to fully verify, but if you try something out I suggest and it doesn't work then feel free to start a discussion in an issue and I'd be glad to help

**Comment by nonchip** [comment]
> I don't think that's too unreasonable given many distros provide 1.0 packages, and Openresty itself depends on openssl 1.0.

the problem with that was that in an effort to support 1.1, the bindings lapis used broke compatibility with some 1.0 API conforming implementations, so it actually didn't work on both 1.1 and 1.0 depending on distro. also openresty actually ships its own version of openssl 1.0 with some resty-specific patches, which to use instead might be a better alternative.

>  it's just that if it's combined with attacks against this project then I'm going to have to say something

I'm sorry about that, it's just I really loved working with lapis for a while until I suddenly ran into those problems and it felt like they were being ignored, rendering it virtually unusable for me, so I decided I had to build an alternative. also more modular because lapis always felt a bit monolithically clunky, including e.g. the rather half-complete subapplication routing that makes implementing api endpoints quite a pain when you can't just get rid of the template for a whole subapp, etc.

**Comment by nonchip** [comment]
just as a heads-up, I started "freeing" the ORM from lapis there: https://github.com/cuddlyrobot/harmonia.
that project is essentially `lapis.db` with any depended lapis modules stubbed out or replaced, made to work either as a submodule for my framework (integrating the config with its system) or standalone (providing the config via a global table, `require`able file or explicitely by calling `config_table_to_fill_in=require'harmonia.config'.make!`).
it's completely untested right now, because I literally just forked lapis and took a sledgehammer of regexes to it :P but I'll test it and work out any bugs asap, just wanted to notify you here, since "I want the lapis ORM but without all of lapis" seems to be a common problem (and @leafo you did a great job with the non-nginx-dependent pgmoon, so pulling another great layer of abstraction away from their (imho) unnecessary dependencies felt the right thing to do)
