### ISSUE TITLE
Session signing  HMAC SHA1

### ISSUE THREAD

**Issue by karai17** [leafo/lapis#589]
With Google's recentish proof of concept in breaking SHA1, it might be wise to change the encryption algorithm used for sessions.

**Comment by leafo** [comment]
sessions aren't encrypted with sha1, but signed with it. But yeah, I agree, we should upgrade. It appears openresty only has a sha1 hmac right now: https://github.com/openresty/lua-nginx-module#ngxhmac_sha1

**Comment by Guard13007** [comment]
Would you be switching to SHA256, or just whatever becomes available whenever it becomes available, or have no idea right now ?

**Comment by leafo** [comment]
Just for some clarification, the sha1 collision vulnerabilities don't affect hmac-sha1 as far as I understand, so this isn't a critical security issue. It would be nice to have a swapable hmac function though, if you want to upgrade. Also, it would be nice to have session encryption, but that's for another ticket.

**Comment by leafo** [comment]
it's now possible to swap out the hmac function for signing sessions, csrf, and objects

**Comment by Guard13007** [comment]
> Just for some clarification, the sha1 collision vulnerabilities don't affect hmac-sha1 as far as I understand, so this isn't a critical security issue.

Because this has been in the back of my mind on and off, I researched it a little bit.

1. [This article](https://vikingvpn.com/blogs/transparency/understanding-googles-sha-1-collision-and-openvpn-hmac-sha1) asserts that HMAC's are fine with *any* hashing algorithm.
2. [Wikipedia](https://en.wikipedia.org/wiki/HMAC) states that the security of HMAC does vary based on the hashing algorithm used, which makes me doubt the first article..
3. The 1st answer on [this StackExchange question](https://crypto.stackexchange.com/questions/26510/why-is-hmac-sha1-still-considered-secure) explains that as long as the secret used for HMAC is not known, it cannot be broken (at least with SHA1 right now, or even if Google's proof of concept became trivially easy to execute).

Seems fine for now, but glad we have the capability to swap it out.
