### ISSUE TITLE
Append to DB array

### ISSUE THREAD

**Issue by turbo** [leafo/lapis#643]
Hi, I'm currently using this approach to append a new item to an array column for postgres. Is this correct, or is there a better way?

```moonscript
torg = Organizations\find @params.id
table.insert torg.customers, cusid.id
torg\update customers: db.array torg.customers
```

**Comment by leafo** [comment]
This is not a good approach because the way you append a new value is not atomic. You may overwrite data written on another worker.

For postgres, you should use the [append function](https://www.postgresql.org/docs/9.1/functions-array.html) for arrays:

```moonscript
torg\update customers: db.raw db.interpolate_query "array_append(customers, ?)", cusid.id
```

Also note, since this uses a `db.raw` object in the update method, the query will automatically refresh that field on the model. So `torg.customers` will hold the new array, and not a `db.raw` object.
