### ISSUE TITLE
how to restart lapis web server on production 

### ISSUE THREAD

**Issue by tanwenliang** [leafo/lapis#650]
how to restart lapis web server on production 

starup:  lapis  server production && 
restart: ?

**Comment by tanwenliang** [comment]
cd path to project && lapis build production  && /data/webserver/openresty/nginx/sbin/nginx -p "$(pwd)"/ -c "nginx.conf.compiled"

**Comment by leafo** [comment]
the `lapis` command has a few helpers for doing this. The current directory must be the same directory as the nginx root.

For a complete restart, you can do

```
lapis term
lapis server
```
`lapis term` will read the current pid file and send a term to that process, shutting everything down cleanly, then you can start it again using `lapis server`. This approach isn't recommended unless necessary, since there will be downtime.. This would be necessary if you've installed a new version of nginx and need to upgrade the running server.

Alternatively, you can use:

```
lapis build
```

To reload all the running code without stopping the nginx master process. Then will allow you to update your application code without dropping any requests. It works by causing all the nginx workers to restart. (this sends a HUP to the nginx master process, iirc)
