### ISSUE TITLE
/usr/local/share/lua/5.1/lapis/html.lua:297: attempt to index local 'w' (a function value)

### ISSUE THREAD

**Issue by Unlimiter** [leafo/lapis#700]
```moonscript
-- app.moon
export require, Widget
require = require'require'.require
lapis = require 'lapis'

import Widget from require 'lapis.html'

class extends lapis.Application
  layout: 'layout' --> Error
  '/': =>
    render: 'index'
```

```moonscript
-- views/layout.moon
class Layout extends Widget
  content: =>
    html_5 ->
      head -> title @title or 'TinyMoon'
      body ->
        widget NavBar --> This is THE line making the error. Oops, totally forgot NavBar is a function.
        @content_for 'inner'
```

```moonscript
-- views/navbar.moon
class NavBar extends Widget
  content: =>
    nav id: 'navbar', ->
      a href: '/', 'Home'
      span '&bull;'
      a href: '/help', 'Help'
```

In #699 I passed the widget's name rather than a function.

p.s. When I passed `NavBar!` instead, the error was the same as in #699.

**Comment by leafo** [comment]
you have no reference to NavBar in the layout, you need to require it.

**Comment by Unlimiter** [comment]
@leafo `import NavBar from require 'views.navbar'` didn't fix it.

**Comment by leafo** [comment]
> @leafo `import NavBar from require 'views.navbar'` didn't fix it.

I think you should spend some more time looking into how require works, and what import does. At least try some debug print statements to get a better understanding.

Your view file returns a class object, not a table containing a class. `import NavBar from require 'views.navbar'` is equivalent to `NavBar = (require"views.navbar").NavBar`. This would assign `nil` because there is no `NavBar` field on the object (the class) that is returned by that module.

Instead you should write: `NavBar = require 'views.navbar`

**Comment by Unlimiter** [comment]
@leafo I freaking forgot.

**Comment by Unlimiter** [comment]
See #699 for the solution.
