### ISSUE TITLE
Unicode characters rendered wrongly

### ISSUE THREAD

**Issue by Unlimiter** [leafo/lapis#704]
"©" => "Â©"
"•" => "â€¢"

**Comment by Unlimiter** [comment]
@leafo I did `meta charset: 'UTF-8'` and `meta http-equiv: 'content-type', content: 'text/html; charset=UTF-8'`, but it still didn't work.

**Comment by leafo** [comment]
I recommend reading the HTML output via the view-source tool in your browser to ensure what you think you're outputting is showing up. It's likely you made a mistake somewhere since even the snippet you shared has a syntax error: `meta http-equiv: 'content-type',`

There's also a rare chance that your editor has written out those characters encoded in something other than UTF-8, but I think it's more likely that you haven't set the content type on the html document correctly.

**Comment by Unlimiter** [comment]
@leafo oops, I meant `'http-equiv'`.

**Comment by Unlimiter** [comment]
@leafo Bruh. I forgot to compile a moon file. Gosh darn it!
